--- 
- name: 1.  Launch instance
  ec2:
    aws_access_key: "{{ access }}"
    aws_secret_key: "{{ secret }}"
    key_name: "{{ keypair }}"
    group: "{{ security_group }}"
    instance_type: "{{ instance_type }}"
    image: "{{ image }}"
    wait: true
    instance_tags:
      Name: Tower-test-POC
    monitoring: no
    region: "{{ region }}"
    vpc_subnet_id: "{{ subnet }}"
    assign_public_ip: yes
  register: ec2
- name: 2. Add new instance to host group
  add_host:
    hostname: "{{ item.public_ip }}"
    groupname: launched
  with_items: "{{ ec2.instances }}"
- name: 3.  Wait for SSH to come up
  wait_for:
    host: "{{ item.public_dns_name }}"
    port: 22
    delay: 60
    timeout: 320
    state: started
  with_items: "{{ ec2.instances }}"
